export const sample_transcript = [
  {
    text: "know it&#39;s really just like anything you",
    duration: "4.00",
    offset: "0.16",
    lang: "en",
  },
  {
    text: "just learn how to do it and you do it I",
    duration: "4.16",
    offset: "2.04",
    lang: "en",
  },
  {
    text: "think the first thing you need to know",
    duration: "5.32",
    offset: "4.16",
    lang: "en",
  },
  {
    text: "is how coding works how things work",
    duration: "5.44",
    offset: "6.20",
    lang: "en",
  },
  {
    text: "together why why are you doing what",
    duration: "3.92",
    offset: "9.48",
    lang: "en",
  },
  {
    text: "you&#39;re doing you know the sky is the",
    duration: "3.08",
    offset: "11.64",
    lang: "en",
  },
  {
    text: "limit you just got to be ready to for",
    duration: "3.28",
    offset: "13.40",
    lang: "en",
  },
  {
    text: "the challenges what&#39;s your name and what",
    duration: "5.04",
    offset: "14.72",
    lang: "en",
  },
  {
    text: "do you do my name is Torrance Evans I&#39;m",
    duration: "6.12",
    offset: "16.68",
    lang: "en",
  },
  {
    text: "a software engineer so uh what advice",
    duration: "5.04",
    offset: "19.76",
    lang: "en",
  },
  {
    text: "would you give anyone who&#39;s trying to",
    duration: "3.96",
    offset: "22.80",
    lang: "en",
  },
  {
    text: "become a software engineer I would say",
    duration: "4.00",
    offset: "24.80",
    lang: "en",
  },
  {
    text: "that is very possible I would say you",
    duration: "3.56",
    offset: "26.76",
    lang: "en",
  },
  {
    text: "know the sky is the limit just got to be",
    duration: "4.00",
    offset: "28.80",
    lang: "en",
  },
  {
    text: "ready to for the challenges what&#39;s the",
    duration: "4.64",
    offset: "30.32",
    lang: "en",
  },
  {
    text: "hardest thing about being a software",
    duration: "4.48",
    offset: "32.80",
    lang: "en",
  },
  {
    text: "engineer I think the hardest thing was",
    duration: "5.24",
    offset: "34.96",
    lang: "en",
  },
  {
    text: "what is actually the you know the thing",
    duration: "4.44",
    offset: "37.28",
    lang: "en",
  },
  {
    text: "that makes it most fun is just problem",
    duration: "3.48",
    offset: "40.20",
    lang: "en",
  },
  {
    text: "solving so the problem solving can be",
    duration: "5.12",
    offset: "41.72",
    lang: "en",
  },
  {
    text: "very difficult and stressful but it&#39;s",
    duration: "5.52",
    offset: "43.68",
    lang: "en",
  },
  {
    text: "also what makes it fun it&#39;s what makes",
    duration: "4.92",
    offset: "46.84",
    lang: "en",
  },
  {
    text: "people want to do it what&#39;s the biggest",
    duration: "4.72",
    offset: "49.20",
    lang: "en",
  },
  {
    text: "misconception people have about software",
    duration: "5.44",
    offset: "51.76",
    lang: "en",
  },
  {
    text: "engineering that you just got to be you",
    duration: "5.24",
    offset: "53.92",
    lang: "en",
  },
  {
    text: "know Dexter&#39;s Laboratory you know what",
    duration: "3.64",
    offset: "57.20",
    lang: "en",
  },
  {
    text: "I&#39;m saying you got to be",
    duration: "4.40",
    offset: "59.16",
    lang: "en",
  },
  {
    text: "is a Super Genius you know it&#39;s really",
    duration: "4.52",
    offset: "60.84",
    lang: "en",
  },
  {
    text: "just like anything you just learn how to",
    duration: "4.60",
    offset: "63.56",
    lang: "en",
  },
  {
    text: "do it and you do it so what&#39;s the basic",
    duration: "6.84",
    offset: "65.36",
    lang: "en",
  },
  {
    text: "level anyone can start coding at the",
    duration: "6.96",
    offset: "68.16",
    lang: "en",
  },
  {
    text: "basic level uh what are the basics to",
    duration: "5.56",
    offset: "72.20",
    lang: "en",
  },
  {
    text: "become a software engineer oh like",
    duration: "5.04",
    offset: "75.12",
    lang: "en",
  },
  {
    text: "skills yeah yeah not just skills but",
    duration: "4.16",
    offset: "77.76",
    lang: "en",
  },
  {
    text: "like so think about like if I want to",
    duration: "3.96",
    offset: "80.16",
    lang: "en",
  },
  {
    text: "become a mechanic today right like maybe",
    duration: "3.60",
    offset: "81.92",
    lang: "en",
  },
  {
    text: "the first thing is just to know like how",
    duration: "2.72",
    offset: "84.12",
    lang: "en",
  },
  {
    text: "to take out the battery or something",
    duration: "2.96",
    offset: "85.52",
    lang: "en",
  },
  {
    text: "like that okay what&#39;s that for like",
    duration: "3.76",
    offset: "86.84",
    lang: "en",
  },
  {
    text: "software engineering I think the first",
    duration: "5.68",
    offset: "88.48",
    lang: "en",
  },
  {
    text: "thing you need to know is how coding",
    duration: "7.44",
    offset: "90.60",
    lang: "en",
  },
  {
    text: "works um how things work together",
    duration: "6.64",
    offset: "94.16",
    lang: "en",
  },
  {
    text: "why why are you doing what you&#39;re doing",
    duration: "4.48",
    offset: "98.04",
    lang: "en",
  },
  {
    text: "first and then you learn a",
    duration: "4.16",
    offset: "100.80",
    lang: "en",
  },
  {
    text: "language which any language works you",
    duration: "5.80",
    offset: "102.52",
    lang: "en",
  },
  {
    text: "know so yeah what are some languages",
    duration: "4.72",
    offset: "104.96",
    lang: "en",
  },
  {
    text: "that are beginner",
    duration: "3.28",
    offset: "108.32",
    lang: "en",
  },
  {
    text: "friendly well the language that I would",
    duration: "3.00",
    offset: "109.68",
    lang: "en",
  },
  {
    text: "say I don&#39;t know if it&#39;s beginner",
    duration: "3.64",
    offset: "111.60",
    lang: "en",
  },
  {
    text: "friendly but if you learn it it makes",
    duration: "5.24",
    offset: "112.68",
    lang: "en",
  },
  {
    text: "all other languages easy so I would say",
    duration: "5.88",
    offset: "115.24",
    lang: "en",
  },
  {
    text: "Java because it really you know writes",
    duration: "4.80",
    offset: "117.92",
    lang: "en",
  },
  {
    text: "everything out allows you to see",
    duration: "3.64",
    offset: "121.12",
    lang: "en",
  },
  {
    text: "everything that&#39;s going on um other",
    duration: "3.64",
    offset: "122.72",
    lang: "en",
  },
  {
    text: "other languages like some of the most",
    duration: "3.12",
    offset: "124.76",
    lang: "en",
  },
  {
    text: "popular ones like python they kind of",
    duration: "3.24",
    offset: "126.36",
    lang: "en",
  },
  {
    text: "shorten things so you don&#39;t really",
    duration: "3.52",
    offset: "127.88",
    lang: "en",
  },
  {
    text: "actually know what&#39;s going on really you",
    duration: "4.20",
    offset: "129.60",
    lang: "en",
  },
  {
    text: "just know what to write so I would say",
    duration: "6.12",
    offset: "131.40",
    lang: "en",
  },
  {
    text: "Java for sure and what is the starting",
    duration: "6.84",
    offset: "133.80",
    lang: "en",
  },
  {
    text: "salary for people getting into uh",
    duration: "5.96",
    offset: "137.52",
    lang: "en",
  },
  {
    text: "software engineering uh I&#39;d say I&#39;d say",
    duration: "5.48",
    offset: "140.64",
    lang: "en",
  },
  {
    text: "average starting probably around",
    duration: "5.72",
    offset: "143.48",
    lang: "en",
  },
  {
    text: "80k yeah probably around 80k what&#39;s the",
    duration: "4.64",
    offset: "146.12",
    lang: "en",
  },
  {
    text: "biggest mistake you&#39;ve seen software",
    duration: "4.20",
    offset: "149.20",
    lang: "en",
  },
  {
    text: "engineers make on their resumes that&#39;s a",
    duration: "4.12",
    offset: "150.76",
    lang: "en",
  },
  {
    text: "tough one I&#39;m I&#39;ll tell you what what",
    duration: "3.72",
    offset: "153.40",
    lang: "en",
  },
  {
    text: "the biggest mistake I made",
    duration: "7.24",
    offset: "154.88",
    lang: "en",
  },
  {
    text: "was not not counting everything like not",
    duration: "6.56",
    offset: "157.12",
    lang: "en",
  },
  {
    text: "feeling like what you did wasn&#39;t really",
    duration: "3.52",
    offset: "162.12",
    lang: "en",
  },
  {
    text: "something worthy to put on the resume I",
    duration: "3.32",
    offset: "163.68",
    lang: "en",
  },
  {
    text: "would say that&#39;s the biggest mistake I",
    duration: "3.96",
    offset: "165.64",
    lang: "en",
  },
  {
    text: "made and what are like three things to",
    duration: "4.40",
    offset: "167.00",
    lang: "en",
  },
  {
    text: "avoid in a software engineering",
    duration: "3.80",
    offset: "169.60",
    lang: "en",
  },
  {
    text: "interview not explaining everything",
    duration: "4.84",
    offset: "171.40",
    lang: "en",
  },
  {
    text: "you&#39;re doing like you got to overc",
    duration: "7.04",
    offset: "173.40",
    lang: "en",
  },
  {
    text: "communicate I would say avoid",
    duration: "5.92",
    offset: "176.24",
    lang: "en",
  },
  {
    text: "quitting like some people get real",
    duration: "4.32",
    offset: "180.44",
    lang: "en",
  },
  {
    text: "frustrated where they just give up avoid",
    duration: "7.60",
    offset: "182.16",
    lang: "en",
  },
  {
    text: "that and avoid uh just getting flustered",
    duration: "7.64",
    offset: "184.76",
    lang: "en",
  },
  {
    text: "like avoid yeah just avoid just stay",
    duration: "6.80",
    offset: "189.76",
    lang: "en",
  },
  {
    text: "mentally prepared stay poised um it&#39;s",
    duration: "7.00",
    offset: "192.40",
    lang: "en",
  },
  {
    text: "okay if you don&#39;t know what&#39;s going on",
    duration: "4.92",
    offset: "196.56",
    lang: "en",
  },
  {
    text: "but really just walk explain your best",
    duration: "5.20",
    offset: "199.40",
    lang: "en",
  },
  {
    text: "you can and just you know just be honest",
    duration: "5.68",
    offset: "201.48",
    lang: "en",
  },
  {
    text: "I think uh Faking It is a lot a big",
    duration: "4.16",
    offset: "204.60",
    lang: "en",
  },
  {
    text: "mistake engineers",
    duration: "3.80",
    offset: "207.16",
    lang: "en",
  },
  {
    text: "make all right appreciate you man he",
    duration: "6.04",
    offset: "208.76",
    lang: "en",
  },
  {
    text: "right man thanks for having me all right",
    duration: "3.84",
    offset: "210.96",
    lang: "en",
  },
];
