export const transcript = {
  success: true,
  transcript: [
    {
      text: "what&#39;s up y&#39;all it&#39;s Annabelle with that",
      duration: "3.92",
      offset: "0.20",
      lang: "en",
    },
    {
      text: "good [ __ ] and I am here with the one and",
      duration: "5.08",
      offset: "1.96",
      lang: "en",
    },
    {
      text: "only Larry June how you doing today",
      duration: "5.64",
      offset: "4.12",
      lang: "en",
    },
    {
      text: "Larry feeling good today uhhuh it&#39;s a",
      duration: "5.00",
      offset: "7.04",
      lang: "en",
    },
    {
      text: "real nice rainy day out here in New York",
      duration: "3.72",
      offset: "9.76",
      lang: "en",
    },
    {
      text: "City you caught the rain what&#39;s your",
      duration: "2.48",
      offset: "12.04",
      lang: "en",
    },
    {
      text: "favorite thing to do when you come out",
      duration: "2.96",
      offset: "13.48",
      lang: "en",
    },
    {
      text: "here to New York man I love just feeling",
      duration: "5.12",
      offset: "14.52",
      lang: "en",
    },
    {
      text: "the energy I go hop out the whip post on",
      duration: "4.52",
      offset: "16.44",
      lang: "en",
    },
    {
      text: "the block with the homies you know what",
      duration: "3.96",
      offset: "19.64",
      lang: "en",
    },
    {
      text: "I&#39;m saying smoke me a joint drink a",
      duration: "4.88",
      offset: "20.96",
      lang: "en",
    },
    {
      text: "smoothie just feel the energy the energy",
      duration: "4.88",
      offset: "23.60",
      lang: "en",
    },
    {
      text: "out here is amazing so I just cool [ __ ]",
      duration: "4.16",
      offset: "25.84",
      lang: "en",
    },
    {
      text: "like that just sliding through seeing",
      duration: "4.84",
      offset: "28.48",
      lang: "en",
    },
    {
      text: "and do new [ __ ] and buying little pieces",
      duration: "5.56",
      offset: "30.00",
      lang: "en",
    },
    {
      text: "here and there and [ __ ] good job New",
      duration: "3.36",
      offset: "33.32",
      lang: "en",
    },
    {
      text: "York numbers you know what I&#39;m talking",
      duration: "2.88",
      offset: "35.56",
      lang: "en",
    },
    {
      text: "about that kind New York knows how to do",
      duration: "3.88",
      offset: "36.68",
      lang: "en",
    },
    {
      text: "it last time I saw you out here was when",
      duration: "3.92",
      offset: "38.44",
      lang: "en",
    },
    {
      text: "you were here at sweet chick doing your",
      duration: "3.28",
      offset: "40.56",
      lang: "en",
    },
    {
      text: "popup with The Alchemist around the",
      duration: "3.20",
      offset: "42.36",
      lang: "en",
    },
    {
      text: "Great Escape and you just told me that",
      duration: "3.68",
      offset: "43.84",
      lang: "en",
    },
    {
      text: "was on your birthday tell me about that",
      duration: "4.24",
      offset: "45.56",
      lang: "en",
    },
    {
      text: "day what was that like it was a a great",
      duration: "4.84",
      offset: "47.52",
      lang: "en",
    },
    {
      text: "experience man the energy was good like",
      duration: "5.36",
      offset: "49.80",
      lang: "en",
    },
    {
      text: "it was no drama sweet chick took care of",
      duration: "5.24",
      offset: "52.36",
      lang: "en",
    },
    {
      text: "us gave us the whole spot the line was",
      duration: "4.32",
      offset: "55.16",
      lang: "en",
    },
    {
      text: "around the corner man I was man it that",
      duration: "3.84",
      offset: "57.60",
      lang: "en",
    },
    {
      text: "was like one of the highlights of my",
      duration: "4.72",
      offset: "59.48",
      lang: "en",
    },
    {
      text: "career honestly coming way over here",
      duration: "4.60",
      offset: "61.44",
      lang: "en",
    },
    {
      text: "from the west coast and seeing that was",
      duration: "4.92",
      offset: "64.20",
      lang: "en",
    },
    {
      text: "like very inspiring to me [ __ ] made me",
      duration: "4.84",
      offset: "66.04",
      lang: "en",
    },
    {
      text: "want to come back out here more it felt",
      duration: "3.40",
      offset: "69.12",
      lang: "en",
    },
    {
      text: "like home for me a little bit you know",
      duration: "3.12",
      offset: "70.88",
      lang: "en",
    },
    {
      text: "what I mean definitely you&#39;ve got a lot",
      duration: "2.92",
      offset: "72.52",
      lang: "en",
    },
    {
      text: "of love and support out here and",
      duration: "3.04",
      offset: "74.00",
      lang: "en",
    },
    {
      text: "especially for that album like I speak",
      duration: "3.28",
      offset: "75.44",
      lang: "en",
    },
    {
      text: "for our whole crew like that was one of",
      duration: "3.44",
      offset: "77.04",
      lang: "en",
    },
    {
      text: "our favorite albums of the past couple",
      duration: "3.44",
      offset: "78.72",
      lang: "en",
    },
    {
      text: "years we talk about it all the time",
      duration: "3.48",
      offset: "80.48",
      lang: "en",
    },
    {
      text: "listen to it all the time like real",
      duration: "3.72",
      offset: "82.16",
      lang: "en",
    },
    {
      text: "incredible piece of work so thank you",
      duration: "3.92",
      offset: "83.96",
      lang: "en",
    },
    {
      text: "for making that come on I appreciate you",
      duration: "3.80",
      offset: "85.88",
      lang: "en",
    },
    {
      text: "appreciate you thank you now we&#39;ve got a",
      duration: "4.32",
      offset: "87.88",
      lang: "en",
    },
    {
      text: "new album on the way doing it for me",
      duration: "4.24",
      offset: "89.68",
      lang: "en",
    },
    {
      text: "which I think is a really cool title",
      duration: "2.96",
      offset: "92.20",
      lang: "en",
    },
    {
      text: "like I really love how much you talk",
      duration: "3.20",
      offset: "93.92",
      lang: "en",
    },
    {
      text: "about self-care caring for yourself tell",
      duration: "3.68",
      offset: "95.16",
      lang: "en",
    },
    {
      text: "me a little bit about that title and",
      duration: "2.96",
      offset: "97.12",
      lang: "en",
    },
    {
      text: "tell me about like times in your life",
      duration: "2.48",
      offset: "98.84",
      lang: "en",
    },
    {
      text: "when you feel like it is important to be",
      duration: "2.88",
      offset: "100.08",
      lang: "en",
    },
    {
      text: "a little selfish and like do things for",
      duration: "4.04",
      offset: "101.32",
      lang: "en",
    },
    {
      text: "you A lot of people forget the reason",
      duration: "5.44",
      offset: "102.96",
      lang: "en",
    },
    {
      text: "why people fell in love with your craft",
      duration: "6.20",
      offset: "105.36",
      lang: "en",
    },
    {
      text: "or whatever you into and um it came from",
      duration: "5.24",
      offset: "108.40",
      lang: "en",
    },
    {
      text: "me just doing me not caring about what",
      duration: "4.64",
      offset: "111.56",
      lang: "en",
    },
    {
      text: "people thought about what I was doing I",
      duration: "5.24",
      offset: "113.64",
      lang: "en",
    },
    {
      text: "was doing exactly what I wanted to do",
      duration: "4.36",
      offset: "116.20",
      lang: "en",
    },
    {
      text: "when I wanted to do it drop when I want",
      duration: "3.40",
      offset: "118.88",
      lang: "en",
    },
    {
      text: "to drop work with who I want to work",
      duration: "3.28",
      offset: "120.56",
      lang: "en",
    },
    {
      text: "with if I want to sing in this random",
      duration: "3.52",
      offset: "122.28",
      lang: "en",
    },
    {
      text: "spot and I just wanted to get back to",
      duration: "3.04",
      offset: "123.84",
      lang: "en",
    },
    {
      text: "that you know I mean I&#39;ve been doing it",
      duration: "3.28",
      offset: "125.80",
      lang: "en",
    },
    {
      text: "for me the whole time but like a whole",
      duration: "4.60",
      offset: "126.88",
      lang: "en",
    },
    {
      text: "project was just like whatever I feel",
      duration: "4.32",
      offset: "129.08",
      lang: "en",
    },
    {
      text: "I&#39;m going do I might wake up in the",
      duration: "3.36",
      offset: "131.48",
      lang: "en",
    },
    {
      text: "morning and say you know I&#39;m put an Al",
      duration: "3.32",
      offset: "133.40",
      lang: "en",
    },
    {
      text: "in the middle of this and boom I might",
      duration: "3.48",
      offset: "134.84",
      lang: "en",
    },
    {
      text: "want to add a verse here or take a verse",
      duration: "3.52",
      offset: "136.72",
      lang: "en",
    },
    {
      text: "off and let the beat rock and it&#39;s doing",
      duration: "3.56",
      offset: "138.32",
      lang: "en",
    },
    {
      text: "it for me and know some [ __ ] I can just",
      duration: "3.16",
      offset: "140.24",
      lang: "en",
    },
    {
      text: "jump into old school and just B some",
      duration: "3.40",
      offset: "141.88",
      lang: "en",
    },
    {
      text: "coners too you know I mean an early",
      duration: "3.16",
      offset: "143.40",
      lang: "en",
    },
    {
      text: "morning drive you know what I mean I",
      duration: "3.24",
      offset: "145.28",
      lang: "en",
    },
    {
      text: "want to press play and be able to just",
      duration: "3.36",
      offset: "146.56",
      lang: "en",
    },
    {
      text: "[ __ ] as long as I&#39;m rocking with it",
      duration: "3.36",
      offset: "148.52",
      lang: "en",
    },
    {
      text: "that&#39;s all that matters 100% And",
      duration: "3.60",
      offset: "149.92",
      lang: "en",
    },
    {
      text: "speaking a little bit more about that",
      duration: "3.52",
      offset: "151.88",
      lang: "en",
    },
    {
      text: "like self-care and discipline are",
      duration: "3.04",
      offset: "153.52",
      lang: "en",
    },
    {
      text: "something that you talk about a lot in",
      duration: "2.96",
      offset: "155.40",
      lang: "en",
    },
    {
      text: "your music what role does selfcare and",
      duration: "4.12",
      offset: "156.56",
      lang: "en",
    },
    {
      text: "discipline play in your career as an",
      duration: "3.88",
      offset: "158.36",
      lang: "en",
    },
    {
      text: "artist and just like your life as a",
      duration: "3.56",
      offset: "160.68",
      lang: "en",
    },
    {
      text: "human being so you know self-care and",
      duration: "3.68",
      offset: "162.24",
      lang: "en",
    },
    {
      text: "discipline is very important you know",
      duration: "3.80",
      offset: "164.24",
      lang: "en",
    },
    {
      text: "self-care is good because you want to in",
      duration: "4.76",
      offset: "165.92",
      lang: "en",
    },
    {
      text: "order to do any of this you got to be",
      duration: "4.48",
      offset: "168.04",
      lang: "en",
    },
    {
      text: "mentally there physically there so you",
      duration: "3.52",
      offset: "170.68",
      lang: "en",
    },
    {
      text: "know you want to take care of yourself",
      duration: "3.84",
      offset: "172.52",
      lang: "en",
    },
    {
      text: "discipline without discipline you know",
      duration: "4.84",
      offset: "174.20",
      lang: "en",
    },
    {
      text: "you can&#39;t really achieve those big goals",
      duration: "3.96",
      offset: "176.36",
      lang: "en",
    },
    {
      text: "and you know I mean you want to be able",
      duration: "3.56",
      offset: "179.04",
      lang: "en",
    },
    {
      text: "if I got to cut something off like say",
      duration: "4.64",
      offset: "180.32",
      lang: "en",
    },
    {
      text: "for instance like I&#39;m making tons of",
      duration: "4.92",
      offset: "182.60",
      lang: "en",
    },
    {
      text: "money the game slow down you got to be",
      duration: "5.56",
      offset: "184.96",
      lang: "en",
    },
    {
      text: "able to stop and have discipline to stop",
      duration: "4.32",
      offset: "187.52",
      lang: "en",
    },
    {
      text: "you know what I mean and you got to have",
      duration: "2.88",
      offset: "190.52",
      lang: "en",
    },
    {
      text: "discipline to keep going as well you",
      duration: "2.76",
      offset: "191.84",
      lang: "en",
    },
    {
      text: "know what I mean CU you might get caught",
      duration: "3.96",
      offset: "193.40",
      lang: "en",
    },
    {
      text: "up in the spotlight and the fans the",
      duration: "4.76",
      offset: "194.60",
      lang: "en",
    },
  ],
};
