export const transcript = {
  success: true,
  transcript: [
    {
      text: "[Applause]",
      duration: "3.93",
      offset: "1.26",
      lang: "en",
    },
    { text: "[Music]", duration: "3.08", offset: "2.11", lang: "en" },
    {
      text: "hi I&#39;m Megan I&#39;m Sierra and I&#39;m Maggie",
      duration: "4.80",
      offset: "5.44",
      lang: "en",
    },
    {
      text: "and from the tastics 2 Welcome to",
      duration: "4.12",
      offset: "7.88",
      lang: "en",
    },
    {
      text: "flipping Friday today we&#39;re going to be",
      duration: "4.00",
      offset: "10.24",
      lang: "en",
    },
    {
      text: "doing another one day tutorial so now",
      duration: "3.80",
      offset: "12.00",
      lang: "en",
    },
    {
      text: "that you guys have your back handspring",
      duration: "2.84",
      offset: "14.24",
      lang: "en",
    },
    {
      text: "we&#39;re going to be teaching you guys how",
      duration: "3.84",
      offset: "15.80",
      lang: "en",
    },
    {
      text: "to get your back tuck in one day before",
      duration: "3.96",
      offset: "17.08",
      lang: "en",
    },
    {
      text: "we get started make sure you subscribe",
      duration: "2.80",
      offset: "19.64",
      lang: "en",
    },
    {
      text: "to our Channel by pressing the button",
      duration: "3.72",
      offset: "21.04",
      lang: "en",
    },
    {
      text: "down below also hit the Bell so you can",
      duration: "5.60",
      offset: "22.44",
      lang: "en",
    },
    {
      text: "be part of our notification Squad and",
      duration: "7.20",
      offset: "24.76",
      lang: "en",
    },
    {
      text: "let&#39;s go ahead and get started",
      duration: "3.92",
      offset: "28.04",
      lang: "en",
    },
    {
      text: "all right so before we get started we",
      duration: "2.56",
      offset: "33.76",
      lang: "en",
    },
    {
      text: "are going to do a quick little",
      duration: "2.84",
      offset: "35.00",
      lang: "en",
    },
    {
      text: "disclaimer I just wanted to start off by",
      duration: "3.32",
      offset: "36.32",
      lang: "en",
    },
    {
      text: "saying Sierra and I when we were",
      duration: "3.40",
      offset: "37.84",
      lang: "en",
    },
    {
      text: "learning our standing back T we did get",
      duration: "3.76",
      offset: "39.64",
      lang: "en",
    },
    {
      text: "it in a day so we know it&#39;s possible",
      duration: "3.44",
      offset: "41.24",
      lang: "en",
    },
    {
      text: "we&#39;re going to be giving you guys a lot",
      duration: "3.00",
      offset: "43.40",
      lang: "en",
    },
    {
      text: "of tips and tricks that we had that we",
      duration: "4.12",
      offset: "44.68",
      lang: "en",
    },
    {
      text: "use and maybe some more so you guys have",
      duration: "4.68",
      offset: "46.40",
      lang: "en",
    },
    {
      text: "more to go off of also I just wanted to",
      duration: "4.44",
      offset: "48.80",
      lang: "en",
    },
    {
      text: "say when we do these how-to videos in",
      duration: "4.00",
      offset: "51.08",
      lang: "en",
    },
    {
      text: "one day that means that you&#39;re probably",
      duration: "3.96",
      offset: "53.24",
      lang: "en",
    },
    {
      text: "going to have to be practicing a large",
      duration: "4.12",
      offset: "55.08",
      lang: "en",
    },
    {
      text: "portion of the day if you actually want",
      duration: "3.92",
      offset: "57.20",
      lang: "en",
    },
    {
      text: "to get the skill in one day if you can&#39;t",
      duration: "4.04",
      offset: "59.20",
      lang: "en",
    },
    {
      text: "that&#39;s fine you can get it in a week a",
      duration: "4.16",
      offset: "61.12",
      lang: "en",
    },
    {
      text: "month keep practicing it just means you",
      duration: "4.76",
      offset: "63.24",
      lang: "en",
    },
    {
      text: "can utilize all the stuff we give you to",
      duration: "4.04",
      offset: "65.28",
      lang: "en",
    },
    {
      text: "work towards getting your standing back",
      duration: "3.16",
      offset: "68.00",
      lang: "en",
    },
    {
      text: "tuck and however fast you can we just",
      duration: "2.76",
      offset: "69.32",
      lang: "en",
    },
    {
      text: "want to make sure you guys are",
      duration: "2.96",
      offset: "71.16",
      lang: "en",
    },
    {
      text: "comfortable safe and you&#39;re confident in",
      duration: "4.12",
      offset: "72.08",
      lang: "en",
    },
    {
      text: "what you&#39;re doing so just make sure you",
      duration: "4.20",
      offset: "74.12",
      lang: "en",
    },
    {
      text: "follow safety guidelines first before",
      duration: "4.77",
      offset: "76.20",
      lang: "en",
    },
    {
      text: "just trying to throw it in one",
      duration: "5.68",
      offset: "78.32",
      lang: "en",
    },
    { text: "[Music]", duration: "3.03", offset: "80.97", lang: "en" },
    {
      text: "day if you&#39;re planning on learning your",
      duration: "4.20",
      offset: "84.36",
      lang: "en",
    },
    {
      text: "back tuck in one day you for sure need a",
      duration: "4.20",
      offset: "86.68",
      lang: "en",
    },
    {
      text: "back handspring it should be consistent",
      duration: "3.84",
      offset: "88.56",
      lang: "en",
    },
    {
      text: "you should have no problems throwing it",
      duration: "2.96",
      offset: "90.88",
      lang: "en",
    },
    {
      text: "and you should be doing it 100% of the",
      duration: "3.64",
      offset: "92.40",
      lang: "en",
    },
    {
      text: "time also start off by warming up a few",
      duration: "3.17",
      offset: "93.84",
      lang: "en",
    },
    {
      text: "back hands",
      duration: "5.17",
      offset: "96.04",
      lang: "en",
    },
    { text: "[Music]", duration: "4.20", offset: "97.01", lang: "en" },
    {
      text: "Springs the next thing you&#39;re going to",
      duration: "3.40",
      offset: "105.60",
      lang: "en",
    },
    {
      text: "want to work on is getting a higher back",
      duration: "3.40",
      offset: "107.40",
      lang: "en",
    },
    {
      text: "hand spring so that&#39;s my first attempt",
      duration: "2.84",
      offset: "109.00",
      lang: "en",
    },
    {
      text: "you can&#39;t really tell the difference",
      duration: "2.48",
      offset: "110.80",
      lang: "en",
    },
    {
      text: "between that and my normal backand",
      duration: "3.36",
      offset: "111.84",
      lang: "en",
    },
    {
      text: "spring just slowly work on getting",
      duration: "3.48",
      offset: "113.28",
      lang: "en",
    },
    {
      text: "higher and higher you want to have as",
      duration: "4.52",
      offset: "115.20",
      lang: "en",
    },
    {
      text: "much air time as possible this is 90% of",
      duration: "4.16",
      offset: "116.76",
      lang: "en",
    },
    {
      text: "what we&#39;re going to say to do and just",
      duration: "3.04",
      offset: "119.72",
      lang: "en",
    },
    {
      text: "work on getting it higher and higher so",
      duration: "4.40",
      offset: "120.92",
      lang: "en",
    },
    {
      text: "do not underestimate doing this honestly",
      duration: "4.36",
      offset: "122.76",
      lang: "en",
    },
    {
      text: "do this as long as you need to do it a",
      duration: "4.40",
      offset: "125.32",
      lang: "en",
    },
    {
      text: "million times the goal of doing this is",
      duration: "4.24",
      offset: "127.12",
      lang: "en",
    },
    {
      text: "that you&#39;re trying to get your feet more",
      duration: "3.20",
      offset: "129.72",
      lang: "en",
    },
    {
      text: "than halfway around before your hands",
      duration: "4.20",
      offset: "131.36",
      lang: "en",
    },
    {
      text: "have to touch the",
      duration: "2.64",
      offset: "132.92",
      lang: "en",
    },
    {
      text: "ground remember to keep challenging",
      duration: "4.24",
      offset: "135.60",
      lang: "en",
    },
    {
      text: "yourself and go up higher each time also",
      duration: "4.32",
      offset: "137.80",
      lang: "en",
    },
    {
      text: "work on keeping your hands up longer",
      duration: "3.20",
      offset: "139.84",
      lang: "en",
    },
    {
      text: "that&#39;s how you&#39;re going to get the",
      duration: "2.20",
      offset: "142.12",
      lang: "en",
    },
    {
      text: "highest back handspring and it&#39;s really",
      duration: "5.60",
      offset: "143.04",
      lang: "en",
    },
    {
      text: "going to start feeling like a back tub",
      duration: "4.32",
      offset: "144.32",
      lang: "en",
    },
    {
      text: "if your high back handsprings are",
      duration: "2.24",
      offset: "150.96",
      lang: "en",
    },
    {
      text: "getting to the point where it&#39;s almost",
      duration: "2.56",
      offset: "152.16",
      lang: "en",
    },
    {
      text: "impossible to rebound out of that means",
      duration: "2.80",
      offset: "153.20",
      lang: "en",
    },
    {
      text: "you&#39;re in a pretty good spot because you",
      duration: "2.68",
      offset: "154.72",
      lang: "en",
    },
    {
      text: "can&#39;t really rebound out of high back",
      duration: "3.12",
      offset: "156.00",
      lang: "en",
    },
    {
      text: "handsprings now we&#39;re going to work on",
      duration: "3.64",
      offset: "157.40",
      lang: "en",
    },
    {
      text: "changing the approach when you&#39;re doing",
      duration: "3.76",
      offset: "159.12",
      lang: "en",
    },
    {
      text: "a back hand spring you focus on jumping",
      duration: "2.96",
      offset: "161.04",
      lang: "en",
    },
    {
      text: "back and here you&#39;re going to really",
      duration: "3.20",
      offset: "162.88",
      lang: "en",
    },
    {
      text: "want to start focusing on jumping up so",
      duration: "3.80",
      offset: "164.00",
      lang: "en",
    },
    {
      text: "it&#39;s totally helpful to do these drills",
      duration: "3.52",
      offset: "166.08",
      lang: "en",
    },
    {
      text: "also practice tucking your knees in",
      duration: "2.92",
      offset: "167.80",
      lang: "en",
    },
    {
      text: "that&#39;s another big difference is that",
      duration: "2.08",
      offset: "169.60",
      lang: "en",
    },
    {
      text: "you&#39;re going to want to tuck your knees",
      duration: "3.52",
      offset: "170.72",
      lang: "en",
    },
    {
      text: "in also find a high spot to look at so",
      duration: "4.28",
      offset: "171.68",
      lang: "en",
    },
    {
      text: "that way you don&#39;t throw your head back",
      duration: "3.20",
      offset: "174.24",
      lang: "en",
    },
    {
      text: "these are all great tips for when you&#39;re",
      duration: "3.60",
      offset: "175.96",
      lang: "en",
    },
    {
      text: "actually transitioning to the back tuck",
      duration: "3.52",
      offset: "177.44",
      lang: "en",
    },
    {
      text: "we have we also like to close our fist",
      duration: "3.40",
      offset: "179.56",
      lang: "en",
    },
    {
      text: "there&#39;s really no right or wrong but we",
      duration: "3.32",
      offset: "180.96",
      lang: "en",
    },
    {
      text: "like to do it it helps give us more",
      duration: "4.78",
      offset: "182.96",
      lang: "en",
    },
    {
      text: "power so go ahead and try that out",
      duration: "10.12",
      offset: "184.28",
      lang: "en",
    },
    { text: "[Music]", duration: "9.26", offset: "187.74", lang: "en" },
    {
      text: "too we always like to tell people to",
      duration: "5.12",
      offset: "194.40",
      lang: "en",
    },
    {
      text: "have a spot if they can so for a spot on",
      duration: "3.96",
      offset: "197.00",
      lang: "en",
    },
    {
      text: "a back tuck you&#39;re going to get spotted",
      duration: "3.32",
      offset: "199.52",
      lang: "en",
    },
    {
      text: "on your back and on your legs they&#39;re",
      duration: "3.48",
      offset: "200.96",
      lang: "en",
    },
    {
      text: "going to throw you up on your back and",
      duration: "3.88",
      offset: "202.84",
      lang: "en",
    },
    {
      text: "then throw your legs over pretty much",
      duration: "3.40",
      offset: "204.44",
      lang: "en",
    },
    {
      text: "the same thing as if you&#39;re spotting a",
      duration: "3.36",
      offset: "206.72",
      lang: "en",
    },
  ],
};
